### ISSUE TITLE
Send raw telemetry to SentryFlow from WASM Plugin

### ISSUE THREAD

**Issue by nandhued** [5GSEC/SentryFlow#15]

**Comment by anurag-rajawat** [comment]
https://github.com/accuknox/dev2/pull/216

**Comment by nandhued** [comment]
Moving to blocked due to https://github.com/5GSEC/SentryFlow/pull/17

**Comment by anurag-rajawat** [comment]
Completed by https://github.com/5GSEC/SentryFlow/pull/17.
