### ISSUE TITLE
SentryFlow E2E Pipeline for API Access Logs

### ISSUE THREAD

**Issue by anurag-rajawat** [5GSEC/SentryFlow#26]
This issue tracks the end-to-end pipeline for ingesting, processing, and visualizing API access logs from end-user clusters to AccuKnox SaaS.

**Key Tasks:**
- [x] Implement support in SentryFlow to ingest raw API access logs from multiple sources. 
   https://github.com/5GSEC/SentryFlow/pull/17
- [x] Develop a mechanism to summarize API events that occur multiple times within a defined timeframe.
   https://github.com/accuknox/dev2/pull/216
- [x] Define schemas for:
    - [x] Raw API access logs for ingestion from various sources.
    https://github.com/5GSEC/SentryFlow/pull/17
    - [x] Summarized API access events.
    https://github.com/accuknox/dev2/pull/216
    - [ ] API request and response payloads for observability API and UI.
    https://github.com/accuknox/observability-api/pull/178
- [x] Persist summarized API access events in a durable storage solution.
https://github.com/accuknox/deo/pull/264
- [x] Integrate the summarized API access logs into the AccuKnox UI for visualization and analysis.
https://github.com/accuknox/observability-api/pull/178

**Comment by nandhued** [comment]
Blocked due to: 
https://github.com/accuknox/observability-api/pull/178
https://github.com/accuknox/deo/pull/264
